language: node_js
node_js:
  - "11"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=247940278ee96e74528e338cb058b98d57588e7f9220497cbc414ba3df92c72f
    - NODE_ENV=test
    - PORT=5037
    - API_VERSION=v1
    - CT_REGISTER_MODE=auto
    - LOCAL_URL=http://127.0.0.1:3001
    - CT_URL=http://127.0.0.1:9000
    - CT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
  - yarn run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
