apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: {name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {name}
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
